Deprecate this repository
aspnet/libuv-package pull request #17
Opened 2017-03-20 21:13 UTC by natemcmaster

To simplify the build setup, we can put both the compile and packaging build steps into one repository.

We will still use separate build configurations on TeamCity to compile for osx/windows/linux etc, but keeping the build code in separate repositories isn't necessary.

Code moved here: https://github.com/aspnet/libuv-build/pull/26

2017-03-20 21:13 UTC, dnfclas commented
@natemcmaster,
Thanks for having already signed the Contribution License Agreement. Your agreement was validated by .NET Foundation. We will now review your pull request.
_Thanks,
.NET Foundation Pull Request Bot_

2017-03-20 23:34 UTC, moozzyk requested changes

2017-03-20 23:34 UTC, moozzyk commented on content/License.txt
> -
This file must not be deleted. It is being linked from: https://www.nuget.org/packages/Libuv/1.9.0 and https://www.nuget.org/packages/Libuv/1.9.1

2017-03-21 00:32 UTC, natemcmaster commented on content/License.txt
> -
Would you be okay if we update its contents to "This file has moved, please see [link to new place]" ?

2017-03-21 02:41 UTC, moozzyk commented on content/License.txt
> -
I don't think I can make this decision. Let's talk to @Eilon tomorrow.

2017-03-21 04:54 UTC, Eilon commented
Is this change necessary? What is motivating it?

2017-03-21 04:56 UTC, natemcmaster commented
Motivated by converting sake to msbuild. We want to simplify how libuv builds, and part of that means we don't need two repos to build and package this library.

2017-03-21 05:04 UTC, Eilon commented on content/License.txt
> -
Yeah that's a no-no. Can we just keep 2 repos but still change away from sake to MSBuild? I get that it isn't pretty, but this stuff here almost never changes anyway.

2017-03-21 05:17 UTC, natemcmaster commented
>  Can we just keep 2 repos

Still in favor of one repo. Two repos is overengineering. If we keep two, when I finish conversion to MSBuild, the only thing this repo would contain is a nuspec file and few dozen lines of powershell that call "nuget.exe pack". (Plus license.txt which is undeletable of course).

2017-03-21 15:40 UTC, moozzyk commented
You could leave just a license in this repo and move everything else, no?

2017-03-21 17:56 UTC, natemcmaster commented
Talked with @Eilon. We'll reverse the direction of the PRs. Move content here from libuv-build.

2017-03-21 17:56 UTC, closed without merging